### PR TITLE
[WIP] Feat/ajaxforgot

### LINKED ISSUE #6: AJAX Forgot
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Send request to training-auth with the goal of the send a email to the user that perform the password reset.

**Describe alternatives you've considered**
No.

**Additional context**
No.

### PR DESCRIPTION
**Pull request by brunooomelo**
# What's the issue linked?

Resolve #6 

# Test cases

Report the test cases that you did in list items:

- [x] Open page
- [x] added text in input
- [ ] Validation Input
- [x] Send form
- [x] Mock endpoint `/forgot_password`
- [x] show message success and clear input

# Did you test this feature on all browsers?

Yes, tested with all the following browsers:

- [ ] Firefox
- [x] Chrome

# Description

I cloned the ButtonCollab and turned it into a button calling it SubmitCollab. A message of success (MessageCollab) was also created.

### CODE REVIEW

**Comment by saulonunesdev** [comment]
Hey @brunooomelo thanks for the PR.

One question, should this file be committed?
[cypress/videos/pages/Forgot/index.test.js.mp4](https://github.com/CollabCodeTech/training-frontend/blob/a0f988ba84c76cab008f345e491d1f336ab18883/cypress/videos/pages/Forgot/index.test.js.mp4)

**Comment by brunooomelo** [comment]
I think so, I looked at the repository and it also exists for signup.

**Comment by marcobrunodev** [comment]
@brunooomelo, please make the following changes:
- change the branch of Feat/ajaxforgot to feature/ajax-forgot;
- write the commits messages on infinitive, instead of added use add;
- always use the emojis;
- always test the interfaces in Firefox and Chrome.

Now I go to make the review code and test interface on my PC.

**Comment by brunooomelo** [comment]
Please do not do code review, I will fix some problems found.

**Pull request closed without merging**
